package dev.vy.drt.tracking;

public enum DetectionEventType {
	CHAT_MESSAGE,
	SCOREBOARD_CHANGE,
	TAB_CHANGE,
	SCREEN_OPEN,
	CONTAINER_SNAPSHOT,
	RUN_STARTED,
	RUN_COMPLETED,
	RUN_EVIDENCE,
	CHEST_PREVIEW,
	CHEST_OPENED,
	LOOT_OBSERVED,
	MODIFIER_OBSERVED,
	WORLD_CHANGED,
	SERVER_CHANGED,
	PERSISTENCE,
	DIAGNOSTIC
}
