package dev.vy.drt.tracking;

public enum DetectionSource {
	AUTHORITATIVE_INTERNAL_IDENTITY,
	CONFIRMED_GUI_COMPONENT,
	CONFIRMED_SCOREBOARD,
	CONFIRMED_COMPLETION,
	STRUCTURED_CHAT,
	CONFIRMED_TAB,
	GUI_TITLE_INFERENCE,
	RECENT_CONTEXT,
	USER_SELECTION,
	FALLBACK_GUESS,
	PLAYER_INVENTORY,
	SERVER_CONTAINER,
	PERSISTENCE,
	SYSTEM,
	NONE
}
